steps:

- id: 'Artifacts Registry'
  name: 'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud artifacts print-settings npm \
      --project=zero65 \
      --repository=npm \
      --location=asia-south1 \
      --scope=@zero65 >> .npmrc

- id: 'Npm Install'
  name: 'gcr.io/cloud-builders/npm'
  script: |
    npx google-artifactregistry-auth
    npm install --omit=dev

- id: 'Docker Build'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/docker/gcloud:$COMMIT_SHA', '-f', 'Dockerfile', '.' ]

- id: 'Docker Push'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/docker/gcloud:$COMMIT_SHA' ]

- id: 'Run Deploy (IOWA)'
  name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'gcloud',
    '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/docker/gcloud:$COMMIT_SHA',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--concurrency', '10', '--timeout', '5', '--max-instances', '1',
    '--memory', '256Mi',
    '--set-env-vars', 'PLATFORM=GCP,PROJECT=$PROJECT_ID,ENV=run,STAGE=prod',
    '--service-account', 'run-gcloud@zero65-419011.iam.gserviceaccount.com'
  ]
